/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsProjectsIdImport } from './routes/projects/$projectsId'
import { Route as ProjectsProjectsIdBacklogImport } from './routes/projects_/$projectsId/backlog'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectsIdRoute = ProjectsProjectsIdImport.update({
  id: '/projects/$projectsId',
  path: '/projects/$projectsId',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectsIdBacklogRoute = ProjectsProjectsIdBacklogImport.update({
  id: '/projects_/$projectsId/backlog',
  path: '/projects/$projectsId/backlog',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectsId': {
      id: '/projects/$projectsId'
      path: '/projects/$projectsId'
      fullPath: '/projects/$projectsId'
      preLoaderRoute: typeof ProjectsProjectsIdImport
      parentRoute: typeof rootRoute
    }
    '/projects_/$projectsId/backlog': {
      id: '/projects_/$projectsId/backlog'
      path: '/projects/$projectsId/backlog'
      fullPath: '/projects/$projectsId/backlog'
      preLoaderRoute: typeof ProjectsProjectsIdBacklogImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$projectsId': typeof ProjectsProjectsIdRoute
  '/projects/$projectsId/backlog': typeof ProjectsProjectsIdBacklogRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$projectsId': typeof ProjectsProjectsIdRoute
  '/projects/$projectsId/backlog': typeof ProjectsProjectsIdBacklogRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/projects/$projectsId': typeof ProjectsProjectsIdRoute
  '/projects_/$projectsId/backlog': typeof ProjectsProjectsIdBacklogRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/$projectsId' | '/projects/$projectsId/backlog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/$projectsId' | '/projects/$projectsId/backlog'
  id:
    | '__root__'
    | '/'
    | '/projects/$projectsId'
    | '/projects_/$projectsId/backlog'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsProjectsIdRoute: typeof ProjectsProjectsIdRoute
  ProjectsProjectsIdBacklogRoute: typeof ProjectsProjectsIdBacklogRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsProjectsIdRoute: ProjectsProjectsIdRoute,
  ProjectsProjectsIdBacklogRoute: ProjectsProjectsIdBacklogRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/projects/$projectsId",
        "/projects_/$projectsId/backlog"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/projects/$projectsId": {
      "filePath": "projects/$projectsId.jsx"
    },
    "/projects_/$projectsId/backlog": {
      "filePath": "projects_/$projectsId/backlog.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
